/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fct;

import javax.swing.JOptionPane;

/**
 *
 * @author WILLIANSOTOCORNOMEND
 */
public class FormPrincipal extends javax.swing.JFrame {
    private Cliente c = new Cliente();
    private ProdutoNacional i = new ProdutoNacional();
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarra = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuCadastrar = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        menuNacional = new javax.swing.JMenuItem();
        menuImportado = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Vendas");

        menuMenu.setText("Menu");
        menuMenu.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        menuCliente.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCliente);

        menuProduto.setText("Produto");
        menuProduto.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        menuNacional.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuNacional.setText("Nacional");
        menuNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNacionalActionPerformed(evt);
            }
        });
        menuProduto.add(menuNacional);

        menuImportado.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuImportado.setText("Importado");
        menuProduto.add(menuImportado);

        menuCadastrar.add(menuProduto);

        menuMenu.add(menuCadastrar);

        menuBarra.add(menuMenu);

        menuAjuda.setText("Ajuda");
        menuAjuda.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        menuSobre.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        menuBarra.add(menuAjuda);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        JOptionPane.showMessageDialog(null,"Desenvolvido por:");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        //FormCliente form = new FormCliente(this, true, c);
        //form.setLocationRelativeTo(null);
        //form.setResizable(false);
        //form.setVisible(true);
        System.out.println(i.getCodigo());
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNacionalActionPerformed
        FormNacional form = new FormNacional (this, true, i);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_menuNacionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new FormPrincipal().setVisible(true);
                FormPrincipal form = new FormPrincipal();
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuImportado;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem menuNacional;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenuItem menuSobre;
    // End of variables declaration//GEN-END:variables
}
