/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fct;

import javax.swing.JOptionPane;

/**
 *
 * @author Willian Sotocorno || Murilo Pereira
 */
public class FormPrincipal extends javax.swing.JFrame {
    
	//Declaração dos vetoroes para armazenar Clientes e Produtos.
	private Cliente[] arrc = new Cliente[20];
    private ProdutoNacional[] arrpn = new ProdutoNacional[50];
    private ProdutoImportado[] arrpi = new ProdutoImportado[30];
    private Venda[] arrv = new Venda[30];        
    
    
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCompra = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        menuBarra = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuCadastrar = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        menuNacional = new javax.swing.JMenuItem();
        menuImportado = new javax.swing.JMenuItem();
        menuDados = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Vendas");
        setBackground(new java.awt.Color(255, 255, 255));

        btnCompra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCompra.setText("Registrar Nova Compra");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnRelatorio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRelatorio.setText("Relatórios de Vendas");

        menuMenu.setText("Menu");
        menuMenu.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        menuCliente.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCliente);

        menuProduto.setText("Produto");
        menuProduto.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        menuNacional.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuNacional.setText("Nacional");
        menuNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNacionalActionPerformed(evt);
            }
        });
        menuProduto.add(menuNacional);

        menuImportado.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuImportado.setText("Importado");
        menuImportado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImportadoActionPerformed(evt);
            }
        });
        menuProduto.add(menuImportado);

        menuCadastrar.add(menuProduto);

        menuMenu.add(menuCadastrar);

        menuDados.setText("Dados");

        jMenuItem1.setText("Salvar em arquivo");
        menuDados.add(jMenuItem1);

        jMenuItem2.setText("Carregar a partir de arquivo");
        menuDados.add(jMenuItem2);

        menuMenu.add(menuDados);

        menuBarra.add(menuMenu);

        menuAjuda.setText("Ajuda");
        menuAjuda.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        menuSobre.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        menuBarra.add(menuAjuda);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(164, Short.MAX_VALUE)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        JOptionPane.showMessageDialog(null,"Desenvolvido por:");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
    	int i = 0;
    	while(arrc[i] != null) {
    		i++;
    	}
    	arrc[i] = new Cliente();
    	//Aqui não passamos um  vetor de clientes pq a gente ta armazenando
    	//Um novo cliente, então a gente só passa a posiçao nula.
        FormCliente form = new FormCliente(this, true, arrc[i]);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        
        i=0;
    	while(arrc[i] != null) {
    		System.out.println(arrc[i].getCpf());
    		i++;
    	}
        
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNacionalActionPerformed
    	int i = 0;
    	while(arrpn[i] != null) {
    		i++;
    	}
    	arrpn[i] = new ProdutoNacional();
        FormNacional form = new FormNacional (this, true, arrpn[i]);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_menuNacionalActionPerformed

    private void menuImportadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImportadoActionPerformed
    	int i = 0;
    	while(arrpi[i] != null) {
    		i++;
    	}
    	arrpi[i] = new ProdutoImportado();
        FormImportado form = new FormImportado (this, true, arrpi[i]);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);        
    }//GEN-LAST:event_menuImportadoActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        int i = 0;
        while(arrv[i] != null){
            i++;
        }
        arrv[i] = new Venda(15);
        FormVenda form = new FormVenda (this, true, arrv[i], arrc, arrpn, arrpi);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_btnCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new FormPrincipal().setVisible(true);
                FormPrincipal form = new FormPrincipal();
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenu menuDados;
    private javax.swing.JMenuItem menuImportado;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem menuNacional;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenuItem menuSobre;
    // End of variables declaration//GEN-END:variables
}
